PROHIBITED_THEMES_KEYWORDS = [
    "tobacco", 
    "cigarette", 
    "cigar", 
    "smoking",
    "gun", 
    "weapon", 
    "firearm", 
    "rifle",
    "prostitute", 
    "escort", 
    "lapdancing",
    "lap dance",
    "lap-dancing", 
    "gentlemen's club",
    "sexual massage", 
    "sex",
    "porn", 
    "nudity", 
    "nude",
    "naked",
    "erotic",
    "violence", 
    "violent",
    "blood", 
    "drugs", 
    "cocaine", 
    "heroin", 
    "meth",
    "weed",
    "cannabis",
    "fuck", 
    "shit", 
    "bitch", 
    "cunt", 
    "asshole",  
    "prescription", 
    "pharmacy",
    "pharmacy only medicine",
    "medicine",
    "infant formula", 
    "baby formula",
    "pyramid scheme", 
    "mlm", 
    "multi-level marketing",
    "extremist", 
    "terrorist",
    "hate", 
    "racist", 
    "nazi", 
    "white power",
    "illegal", 
    "counterfeit", 
    "pirated",
    "piracy"
]

AGE_PROHIBITED_THEMES_KEYWORDS = [
    "alcohol", 
    "beer", 
    "vodka", 
    "whiskey", 
    "wine",  
    "gambling", 
    "casino", 
    "betting", 
    "poker", 
    "slots",  
    "hfss", 
    "junk food", 
    "soda", 
    "energy drink",
    "slimming", 
    "diet pill", 
    "weight loss"
]

RESTRICTED_THEMES_KEYWORDS = [
    "supplement", 
    "protein", 
    "vitamin", 
    "cosmetic", 
    "surgery",
    "hair restoration", 
    "botox", 
    "skincare", 
    "cream",
    "slimming", 
    "diet pill", 
    "weight loss", 
    "fat burner",
    "fast food", 
    "burger", 
    "fried chicken", 
    "pizza", 
    "soda",
    "vape", 
    "e-cig", 
    "ecigarette",
    "cbd", 
    "cannabidiol", 
    "hemp oil",
    "crypto",
    "bitcoin", 
    "ethereum", 
    "token", 
    "nft",
    "political", 
    "vote", 
    "election", 
    "referendum",
    "religion", 
    "church", 
    "mosque", 
    "temple", 
    "crucifix", 
    "allah",
    "swastika",
    "explosion", 
    "fire", 
    "broken glass", 
    "graffiti", 
    "underwear", 
    "swimwear",
    "sexual position", 
    "breast", 
    "bottom", 
    "sex object",
    "tfl", 
    "uber", 
    "taxi", 
    "private hire",
    "payday loan", 
    "short term lending",
    "petroleum", 
    "oil company", 
    "fossil fuel",
    "qrcode", 
    "qr code",
    "eco", 
    "carbon neutral", 
    "sustainable", 
    "green",
]

RESTRICTED_COUNTRY_KEYWORDS = [
    "afghanistan", 
    "afghan",
    "armenia", 
    "armenian",
    "azerbaijan", 
    "azerbaijani", 
    "azeris",
    "brunei",
    "iran", 
    "iranian", 
    "persia", 
    "persian",
    "karabakh", 
    "nagorno-karabakh",
    "khojaly",
    "mauritania", 
    "mauritanian",
    "nigeria", 
    "nigerian", 
    "naija",
    "pakistan", 
    "pakistani",
    "qatar", 
    "qatari", 
    "doha",
    "saudi", 
    "saudi arabia", 
    "ksa", 
    "kingdom of saudi arabia",
    "somalia", 
    "somali",
    "sudan", 
    "sudanese",
    "uae", 
    "united arab emirates", 
    "dubai", 
    "abu dhabi", 
    "emirati",
    "yemen", 
    "yemeni"
]

CHILD_AUDIENCE_KEYWORDS = [
    "child",
    "children", 
    "kid", 
    "kids", 
    "toddler",
    "teen", 
    "teenager", 
    "under 18", 
    "u18", 
    "school",
    "nursery", 
    "youth", 
    "young people"
]

CHILD_PLACEMENT_KEYWORDS = [
    "school", 
    "nursery", 
    "kindergarten", 
    "daycare",
    "primary school", 
    "secondary school",
    "college", 
    "university", 
    "campus",
    "playground", 
    "play area", 
    "sports ground", 
    "youth club",
    "children's centre", 
    "youth centre",
    "kids zone", 
    "kids club", 
    "soft play",
    "after school", 
    "summer camp", 
    "holiday club"
]


